---

- hosts: all
  become: true
  tasks:

  - name: update
    apt:
      update_cache: yes

  - name: install apache2 package
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
