---

- hosts: all
  become: true
  roles:
    - todos 

- hosts: workstations
  become: true
  roles:
    - workstations 

- hosts: webservers
  become: true
  roles:
    -  webservers

- hosts: fileservers
  become: true
  roles:
    - fileservers

- hosts: dbservers
  become: true
  roles:
    - dbservers
