---

- hosts: all
  become: true
  tasks:

  - name: update and htop and vim
    apt:
      name: 
        - vim
        - htop
      state: latest
      update_cache: yes

- hosts: webservers
  become: true
  tasks:

  - name: install apache2 package
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest

- hosts: fileservers
  become: true
  tasks:

  - name: install samba package
    apt:
      name:
        - samba
        - samba-common
      state: latest

- hosts: dbservers
  become: true
  tasks:

  - name: install mariadb
    apt:
      name:
        - mariadb-server
      state: latest
