- name: update and htop and vim
  apt:
    name: 
      - vim
      - htop
    state: latest
    update_cache: yes

- name: index
  copy:
    src: index.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644

- name: usuario vromani
  user:
    name: vromani
    groups: root
    shell: /bin/bash
    password: "$y$j9T$I/5sVlEgWpaZgTI1fTGU00$QPgtBMIw1PFDM7bmaUPq7Ppl3b6Cw3PR.UPmTN5iHL5"
     
- name: add ssh key for vromani
  authorized_key:
    user: vromani
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMACbCFxJG93dVgBJzxwS4uk5t3VzJIcVuwbIauG1Xz4 bbvauser@nbl645d8685d2ca"

- name: add sudoers file for vromani
  copy:
    src: sudoer_vromani
    dest: /etc/sudoers.d/vromani
    owner: root
    group: root
    mode: 0440
